package day08_test

import (
	"strings"
	"testing"

	"github.com/jonavdm/aoc-2024/day08"
	_ "github.com/jonavdm/aoc-2024/testing"
	"github.com/stretchr/testify/assert"
)

func TestRun(t *testing.T) {
	var test []string = strings.Split(`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`, "\n")
	assert.Equal(t, [2]interface{}{14, 34}, day08.Run(test))
}
